name: flutter_earth
description: A Flutter earth widget.
version: 0.0.5
author: Zebiao Hu <zesage@gmail.com>
homepage: https://github.com/zesage/flutter_earth

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/city.json
    - assets/google_map_north_pole.png
    - assets/google_map_south_pole.png
